name: Publish

on:
  workflow_run:
    workflows: ["Quality Gate"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install -g @wix/cli
      - run: wix login --api-key ${{ secrets.WIX_CLI_TOKEN }}
      - run: wix publish --verbose
